language: android
script: "./gradlew testDebug"
android:
  components:
    - build-tools-21.1.2
    - android-21
    - extra-android-m2repository
    - extra-google-google_play_services
    - extra-google-m2repository
